development:
  host: 127.0.0.1
  database: bootstrap4_playground_devel
  username: bootstrap4_playground_devel
  password: skelet

test:
  host: 127.0.0.1
  database: bootstrap4_playground_test
  username: bootstrap4_playground_test
  password: skelet

production:
  host: 127.0.0.1
  database: bootstrap4_playground_production
  username: bootstrap4_playground_production
  password: <?=sha1(SECRET_TOKEN."Very_Sophisticated_Production_Password_Hiding")?>
